package it.mpace.thomas.screen;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.Screen;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.ScreenUtils;

import it.mpace.thomas.ThomasMain;
import it.mpace.thomas.actors.BoomerangThrower;
import it.mpace.thomas.actors.Enemy;
import it.mpace.thomas.actors.Giant;
import it.mpace.thomas.actors.Player;
import it.mpace.thomas.actors.Player.State;
import it.mpace.thomas.actors.StickFighter;
import it.mpace.thomas.data.LevelInfo;
import it.mpace.thomas.res.AudioRes;
import it.mpace.thomas.res.GameControlRes;
import it.mpace.thomas.res.PlayerRes;
import it.mpace.thomas.sprite.FloatingScore;
import it.mpace.thomas.sprite.HitEffect;
import it.mpace.thomas.sprite.Knife;
import it.mpace.thomas.sprite.PotProjectile; // NEW

public abstract class LevelScreen implements Screen{

	public Player player;

	public SpriteBatch batch;
	public Texture background;
	public OrthographicCamera camera;

	public Array<Enemy> enemies = new Array<Enemy>();

	public Array<Knife> knives = new Array<>();
	// Projectiles generated by ExplodingBall explosions
	public Array<PotProjectile> potProjectiles = new Array<>();

	public Texture whitePixel = null;
	public Enemy boss;
	
	public ShapeRenderer shapeRenderer;
	public boolean introActive = true;
	public float introTimer = 0;
	public final float READY_DURATION = 8.0f;

	public OrthographicCamera hudCamera;

	// Aggiungi come variabile di istanza
	public BitmapFont font;
	
	protected float transitionTimer = 0;
	protected boolean isLevelComplete = false;
	protected int knifeThrowersSpawned = 0; // Contatore per i Knife Throwers spawnati
	protected ThomasMain game = null;
	
	protected float spawnTimer;
	
	protected LevelInfo levelInfo;
	
	protected float deathTimer;
	
	private boolean introTransitionHandled = false; // Flag per assicurare che la sincronizzazione dell'intro avvenga una sola volta
	

	
	public Array<HitEffect> hitEffects = new Array<HitEffect>();
	public Array<FloatingScore> floatingScores = new Array<>();
	
	public LevelScreen(ThomasMain g) {
		this.game = g;
		this.camera = new OrthographicCamera();
		camera.setToOrtho(false, 256, 256);
		this.batch = this.game.batch;
		this.shapeRenderer = new ShapeRenderer();
		this.font = this.game.font; // Carica il font di default
		// Inizializza la camera per l'HUD
		hudCamera = new OrthographicCamera();
		hudCamera.setToOrtho(false, 256, 256); // Stessa risoluzione logica, ma fissa
		Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);// Crea una texture 1x1 pixel bianca programmata
		pixmap.setColor(Color.WHITE);
		pixmap.fill();
		whitePixel = new Texture(pixmap);
		pixmap.dispose();
	}
	
	@Override
	public void render(float delta) {
		float frameTime = Math.min(delta, 1/60f); 
		 // 2. Pulizia schermo
	    ScreenUtils.clear(0, 0, 0, 1);
		update(frameTime);
		draw(frameTime);
	}
	
	
	public void update(float dt) {
		if (introActive) {
			this.handleIntro(dt);
			// ensure we reset the transition flag while intro is running
			introTransitionHandled = false;
			return; // Salta il resto dell'update (nemici, timer di gioco, ecc.)
		}
		// If we just exited the intro, perform a one-time sync to respawnX/camera to avoid
		// subordinate logic moving player back to levelBeginX unexpectedly
		if (!introTransitionHandled && this.levelInfo != null) {
			this.player.position.x = this.levelInfo.getRespawnX();
			this.player.currentState = Player.State.IDLE;
			this.player.autoWalking = false;
			// orientamento coerente per il piano
			this.player.facingRight = (this.levelInfo.getFloor() == 2 || this.levelInfo.getFloor() == 4) ? true : false;
			this.camera.position.x = this.player.position.x;
			this.camera.update();
			introTransitionHandled = true;
//			if (GameControlRes.debugMode) {
//				System.out.println("[IntroSync] forced PlayerX=" + this.player.position.x + " CameraX=" + this.camera.position.x + " Floor=" + this.levelInfo.getFloor());
//			}
		}

		// Debug: quando l'intro è finita, stampiamo la posizione del player e della camera per diagnosticare teletrasporti
//		if (GameControlRes.debugMode) {
//			String bossState = (boss != null) ? ("active=" + boss.isActive() + ", state=" + boss.getState()) : "no-boss";
//			System.out.println("[Update] PlayerX=" + player.position.x + " CameraX=" + camera.position.x + " " + bossState);
//		}
		// 1. GESTIONE TEMPO DI GIOCO
		GameControlRes.gameTime -= GameControlRes.TIME_SPEED * dt;
		if (GameControlRes.gameTime <= 0) {
			GameControlRes.gameTime = 0;
			if (player.currentState != Player.State.DEAD) {
				player.triggerDeath();
			}
		}
		// 2. UPDATE DEL GIOCATORE
		player.update(dt);
		// 3. GESTIONE LIBERAZIONE (Se Thomas si libera, tutti i Gripper che lo tengono
		// muoiono)
		if (player.currentState != State.DEAD && player.checkAndResetLiberation()) {
			this.handleGrabbingEnemies(dt);
		}

		this.handleEnemies(dt);
		//this.enemyManager.update(dt, player);
		this.handleKnives(dt);
		this.handlePotProjectiles(dt); // NEW: update pot fragments and collisions
		this.handleBoss(dt);
		// Ensure level transition logic runs every frame (some levels rely on boss state or other checks)
		this.startLevelTransition(dt);
		// Debug: print transition-related state when debugMode is on
//		if (GameControlRes.debugMode) {
//			String bossState = (boss != null) ? ("active=" + boss.isActive() + ", state=" + boss.getState()) : "no-boss";
//			System.out.println("[LevelScreen.update] PlayerX=" + player.position.x + " PlayerY=" + player.position.y + " CameraX=" + camera.position.x + " isLevelComplete=" + isLevelComplete + " transitionTimer=" + transitionTimer + " goalX=" + (levelInfo!=null?levelInfo.getGoalX():"null") + " " + bossState);
//		}
		// 6. CAMERA E SPAWN
		updateCamera();
		handleSpawning(dt);
	}
	
	protected abstract void handleIntro(float dt);
	protected abstract void handleGrabbingEnemies(float dt);
	protected abstract void handleEnemies(float dt);
	protected abstract void handleKnives(float dt);
	// --- PotProjectile handling ---
	protected void handlePotProjectiles(float dt) {
		for (int i = potProjectiles.size - 1; i >= 0; i--) {
			PotProjectile p = potProjectiles.get(i);
			p.update(dt);
			if (p.active && p.hitbox.overlaps(player.hurtbox) && player.currentState != Player.State.DEAD) {
				// Danno esempio: 10
				player.takeHit(10f, this, p.position.x, p.position.y);
				p.active = false;
			}
			if (!p.active) potProjectiles.removeIndex(i);
		}
	}
	protected abstract void handleBoss(float dt);
	protected abstract void handleSpawning(float dt);
	public abstract boolean isExceedingBoss(float x);

	public abstract void draw(float dt);
	public abstract void startLevelTransition(float dt);
	public abstract Enemy getBoss() ;

	public void killAllEnemies() {
		// Colleziona e uccide tutti i nemici
		for (Enemy e : enemies) {
			e.hp = 0; // Imposta HP a 0 per farli morire
			// Se vuoi, puoi anche aggiungere effetti di morte qui
		}
		enemies.clear(); // Rimuove tutti i nemici dalla lista
		// Pulizia aggiuntiva: rimuove proiettili ed effetti associati al livello
		if (this.knives != null) this.knives.clear();
		if (this.hitEffects != null) this.hitEffects.clear();
		if (this.floatingScores != null) this.floatingScores.clear();
		if (this.potProjectiles != null) this.potProjectiles.clear();
		if(this.boss != null) {
			this.boss.hp = 0; // Uccidi anche il boss
		}
	}
	
	protected void updateCamera() {
		// La camera segue la posizione X del giocatore
		if (player.currentState == Player.State.DEAD) {
			return; // Esci subito: la camera resta ferma dov'era al momento del colpo ferale
		}
		camera.position.x = player.position.x;
		//CLAMP della camera ai limiti del livello
		// Calcola il limite minimo e massimo dinamicamente
	    float minX = Math.min(levelInfo.getGoalX(), levelInfo.getRespawnX());
	    float maxX = Math.max(levelInfo.getGoalX(), levelInfo.getRespawnX());

	    // Se vuoi permettere alla camera di vedere un po' oltre il respawn/goal:
	    if (camera.position.x < minX) camera.position.x = minX;
	    if (camera.position.x > maxX) camera.position.x = maxX;

		camera.update();
	}
	
	public void drawDebugShapes() {
		shapeRenderer.setProjectionMatrix(camera.combined);
		shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
		// Player Hitbox (Rossa) e Hurtbox (Verde)
		shapeRenderer.setColor(Color.RED);
		shapeRenderer.rect(player.hitbox.x, player.hitbox.y, player.hitbox.width, player.hitbox.height);
		shapeRenderer.setColor(Color.GREEN);
		shapeRenderer.rect(player.hurtbox.x, player.hurtbox.y, player.hurtbox.width, player.hurtbox.height);
		shapeRenderer.setColor(Color.RED);
	    
		// Nemici (Gialla)
		shapeRenderer.setColor(Color.YELLOW);
		for (Enemy e : enemies) {
			shapeRenderer.rect(e.hurtbox.x, e.hurtbox.y, e.hurtbox.width, e.hurtbox.height);
			Rectangle attackBox = e.getHitBox();
	        
	        // La disegniamo solo se ha dimensioni reali (non è 0,0,0,0)
	        if (attackBox != null && attackBox.width > 0) {
	        	shapeRenderer.setColor(Color.CYAN);
	            shapeRenderer.rect(attackBox.x, attackBox.y, attackBox.width, attackBox.height);
	            shapeRenderer.setColor(Color.YELLOW);
	        }
	        
		}
		// AGGIUNGI QUESTA RIGA: Disegna esplicitamente quella del Boss
		if (boss != null) {
		    // disegna hurtbox (presente per tutte le implementazioni)
		    if (boss.hurtbox != null) {
		        shapeRenderer.rect(boss.hurtbox.x, boss.hurtbox.y, boss.hurtbox.width, boss.hurtbox.height);
		    }
		    // draw hitbox in modo sicuro (evita chiamate ripetute)
		    Rectangle bHit = boss.getHitBox();
		    if (bHit != null && bHit.width > 0) {
		        shapeRenderer.setColor(Color.CYAN);
		        shapeRenderer.rect(bHit.x, bHit.y, bHit.width, bHit.height);
		        shapeRenderer.setColor(Color.YELLOW);
		    }
		}
		// Coltelli (Ciano)
		shapeRenderer.setColor(Color.CYAN);
		for (Knife k : knives) {
			shapeRenderer.rect(k.hitbox.x, k.hitbox.y, k.hitbox.width, k.hitbox.height);
		}
		shapeRenderer.end();
	}

	public void drawUI() {
		if (introActive) {
	        // Effetto lampeggiante basato sul tempo
	        float alpha = (float) Math.abs(Math.sin(introTimer * 10)); 
	        font.setColor(1, 1, 0, alpha); // Giallo con trasparenza variabile
	        font.draw(batch, "GET READY!", 100, 150);
	        font.setColor(Color.WHITE); // Reset
	    }
		// 1. FASCIA NERA SUPERIORE
		// Disegniamo da y=200 a y=256 (altezza 56 pixel) su tutta la larghezza (256)
		batch.setColor(Color.BLACK);
		batch.draw(whitePixel, 0, 0, 256, 56);
		//batch.setColor(Color.WHITE); // Resetta il colore per i testi

		// 2. TESTI (Ora saranno sempre su sfondo nero)
		font.setColor(Color.CYAN); // Colore classico 1P/ENEMY
		font.draw(batch, "1P - "+String.format("%06d", (int) GameControlRes.score), 5, 54);
		// Score Massimo (High Score)
		font.setColor(Color.RED);
		font.draw(batch, "TOP - " + String.format("%06d", (int) GameControlRes.getGlobalHiScore()), 80, 54);
		
		// Timer a destra
		font.setColor(Color.YELLOW);
		font.draw(batch, "TIME: " + (int) GameControlRes.gameTime, 200, 54);
		//font.draw(batch, , 24, 54);
		drawEnergyBar(batch, GameControlRes.energy, 5, 35, Color.ORANGE, "PLAYER");
		drawEnergyBar(batch, (boss != null ? boss.getHp() : 0),  5, 20, Color.PURPLE, "BOSS  ");

		//font.draw(batch, "BOSS", 160, 54);
		font.draw(batch, "LIVES: "+String.valueOf((int) GameControlRes.lives), 205, 20);
		int floorSpace = 20;
		int floorX=105;
		int floorY=23;
		for(int i=0;i<5;i++) {
			if(this.levelInfo.getFloor()==(i+1)) {
				this.drawFloorSymbol(batch, floorX+(i*floorSpace)+2,floorY, Color.YELLOW, i+1);
			}else if(this.levelInfo.getFloor()>(i+1)) {
				this.drawFloorSymbol(batch, floorX+(i*floorSpace)+2,floorY, Color.GREEN, i+1);
			}else {
				this.drawFloorSymbol(batch, floorX+(i*floorSpace)+2,floorY, Color.WHITE, i+1);
			}
//			if(i<4) {
//				font.draw(batch, "-->", floorX+(i*floorSpace)+8, floorY);
//			}
		}
		// 2. Disegno icone (Teste di Thomas)
		float startX = 205; // Allineato sotto la scritta LIVES
		float yPos = 30;     // Spazio in basso nell'HUD
		float spacing = 12; // Distanza tra le icone
		
		// Disegniamo una testa per ogni vita (stile arcade: vite totali)
		for (int i = 0; i < GameControlRes.lives; i++) {
		    batch.draw(PlayerRes.thomasHeadFrame, startX + (i * spacing), yPos, 10, 10);
		}

		if (GameControlRes.isMuted) {
		    font.setColor(Color.RED);
		    font.draw(batch, "MUTE", 220, 10); // In alto a destra nell'HUD nero
		}
		if (GameControlRes.debugMode) {
		    font.setColor(Color.RED);
		    font.draw(batch, "DEBUG", 190, 10); // In alto a destra nell'HUD nero
		}
	}
	
	public void drawEnergyBar(SpriteBatch batch, float energyValue, float x, float y, Color color, String label) {
		font.setColor(color);
		
	    font.draw(batch, label, x, y+5);
	    float energyWidth = (energyValue / 100f) * 60; // Max 60px
	    
	    int spacing = label.length()*6;
	    batch.setColor(Color.GRAY);
	    batch.draw(whitePixel, x+spacing, y, 60, 8);
	    batch.setColor(color);
	    batch.draw(whitePixel, x+spacing, y, energyWidth, 8);
	    batch.setColor(Color.WHITE); // Resetta sempre il colore del batch!
	    font.setColor(Color.WHITE);
	}
	
	public void drawFloorSymbol(SpriteBatch batch, float x, float y, Color color, int floor) {
		font.setColor(Color.CYAN);
		
	    font.draw(batch, String.valueOf(floor)+"F", x-3, y+15);
	    batch.setColor(color);
	    batch.draw(whitePixel, x, y, 5, 5);
	     // Resetta sempre il colore del batch!
	    if(floor<5) {
	    	batch.setColor(Color.GRAY);
	    	batch.draw(whitePixel,x+5,y+2,20,1);
	    	batch.draw(whitePixel,x+17,y+3,2,1);
	    	batch.draw(whitePixel,x+17,y+1,2,1);
	    	batch.draw(whitePixel,x+17,y+4,1,1);
	    	batch.draw(whitePixel,x+17,y,1,1);
	    }
	    batch.setColor(Color.WHITE);
	    font.setColor(Color.WHITE);
	}
	
	protected void handleDeath(float dt) {
		if (player.position.y > this.levelInfo.getGroundY() + 1) {
			return;
		}

		deathTimer += dt;
		if (deathTimer >= 3.0f) {
			if (GameControlRes.lives > 1) { // Nota: controlliamo se ha ancora vite
				GameControlRes.decrementLives(); // Sottrai una vita
				GameControlRes.resetForRespawn();
				knives.clear();
				enemies.clear();
				floatingScores.clear();
				hitEffects.clear();
	            knifeThrowersSpawned = 0; // Reset del contatore dei KnifeThrower
				player.respawn(this.levelInfo.getRespawnX(), this.levelInfo.getGroundY());
				player.facingRight = (this.levelInfo.getFloor() == 2||this.levelInfo.getFloor() == 4);
				switch (this.levelInfo.getFloor()) {
				case 1:
					boss = new StickFighter(this.levelInfo.getGoalX(), this.levelInfo.getGroundY());
					boss.setActive(false); // Il boss rimane inattivo finché non raggiungi il punto di spawn
					boss.facingRight = true;
					break;
				case 2:
					boss = new BoomerangThrower(this.levelInfo.getGoalX(), this.levelInfo.getGroundY());
					boss.setActive(false); // Il boss rimane inattivo finché non raggiungi il punto di spawn
					boss.facingRight = false;
					break;
				case 3:
					boss = new Giant(this.levelInfo.getGoalX(), this.levelInfo.getGroundY());
					boss.setActive(false); // Il boss rimane inattivo finché non raggiungi il punto di spawn
					boss.facingRight = true;
					break;
					//TODO altri case
				}
				camera.position.x = player.position.x;
				deathTimer = 0;
			} else {
				// Logica Game Over definitiva
				GameControlRes.lives = 0;
				GameControlRes.saveHighScore((int)GameControlRes.score);
				System.out.println("GAME OVER");
				if (GameControlRes.isHighScore((int)GameControlRes.score)) {
			        game.setScreen(new NameEntryScreen(game, (int)GameControlRes.score));
			    } else {
			        game.setScreen(new GameOverScreen(game));
			    }

			}
		}
	}
	
	
	
	protected void handleGameOver() {
		AudioRes.stopMusic(AudioRes.bgm_main_theme);
		AudioRes.playMusic(AudioRes.bgm_game_over);
		if (Gdx.input.isKeyJustPressed(Input.Keys.ENTER)) {
			GameControlRes.fullReset(); // Metodo che azzera vite, score ed energia
			knives.clear();
			enemies.clear();
			knifeThrowersSpawned = 0; 
			player.respawn(this.levelInfo.getRespawnX(), this.levelInfo.getGroundY());
			player.facingRight = false;
			camera.position.x = player.position.x;

		}
	}

}
